name: Bug report
description: Report a reproducible issue
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Clear, concise summary of the issue.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Exact commands/keys/screens to reproduce.
      placeholder: |
        1. Run ...
        2. Select ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include OS, terminal, Node.js, codex version.
      placeholder: |
        OS:
        Terminal:
        Node:
        codex -V:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/screenshots
      description: Any useful output or screenshots.
